### ISSUE TITLE
Support for new 30.01 and 30.0 version.

### ISSUE THREAD

**Issue by trueauracoral** [JustOff/github-wc-polyfill#60] opened 2022-03-21 23:17 UTC
I installed palemoon on my laptop and it prompted me to install the new version of palemoon just as I was about to install this extension. So I did install the new version and then finally tried to install this extension and it told me it didn't support 30.0. I also tried later on 30.01 the next day when that prompt came to me. 

I am trying to install here in the github releases section. https://addons.palemoon.org is down for some reason.

So it would be nice if this extension somehow supported these new versions.

It appears that github now lets me at least sign in and make issues. Just pasting and importing files doesn't work and I can't access settings and stuff. gitlab.com doesn't work at all. So I would like this extension to work in 30.0 and 30.1.

**Comment by TiberiumFusion** [comment] 2022-03-21 23:46
See issue #59 (read the latest posts)

Moonchild announced a rollback to Pale Moon 29.4 and upcoming 29.4.x security update. The official downloads have already been updated and Pale Moon 30 is no longer available from the website. Since profile corruption can occur when downgrading between major releases, you should use a v29 backup of your profile (if you have one), or recreate a new, fresh profile in v29. Moonchild has not yet commented on this issue. He may eventually offer official guidance for those of us who took at the v30 update and now have v30 profiles.

> https://addons.palemoon.org is down for some reason.

See: https://forum.palemoon.org/viewtopic.php?f=1&t=28044

**Comment by Vangelis66** [comment] 2022-03-21 23:52
Duplicate of #59 😞 (why do people never search first **ALL open+closed** issues **before** filing new ones?)

> https://addons.palemoon.org/ is down for some reason.

So is https://addons-legacy.palemoon.org/ ...
FTR, this very extension was NEVER hosted on the official **PM extensions repo** (APMO), only available since day 1 here on GitHub...

As I am typing this, I became aware **TiberiumFusion** beat me by mere seconds 😜 ; anyhow...

**Comment by SeaHOH** [comment] 2022-03-22 04:07
Duplicate of #59

**Closed by SeaHOH** 2022-03-22 04:07 UTC

**Comment by trueauracoral** [comment] 2022-03-22 04:46
I use a portable version of palemoon which actually doesn't work portable when I tried it, moving the directory with a usb stick to this laptop. Doesn't save any settings for some reason. So I *think* the [backup tool](https://www.palemoon.org/backuptool.shtml) won't work because it's not for portable. If I wanted to go to a different version I would need to install and reconfigure, which I guess I will find time for myself to do. I really want to use this extension.

Thank you very much for the advice/tips on what to do. Sorry that I forgot to check other issues.

**Comment by SeaHOH** [comment] 2022-03-22 07:11
I will not pay for MCP's miss, [this](https://github.com/JustOff/github-wc-polyfill/files/8321954/github-wc-polyfill-1.2.17.xpi.zip) is just for you.

**Comment by LigH-de** [comment] 2022-05-10 15:10
Version 31.0 has been released. Let's test whether it is still required for some sites...
