### ISSUE TITLE
incompatible with waterfox

### ISSUE THREAD

**Issue by ruboard** [JustOff/github-wc-polyfill#39] opened 2021-12-04 08:17 UTC
Waterfox classic does not create accessibility.lastLoadDate by default
without this parameter, the extension does not work.
if you create this parameter, then everything will work fine, but it will stop working multi-process
please fix it.

**Comment by JustOff** [comment] 2021-12-04 09:36
Duplicate of #18.

**Closed by JustOff** 2021-12-04 09:36 UTC
