### ISSUE TITLE
Network graph no longer works

### ISSUE THREAD

**Issue by rofl0r** [JustOff/github-wc-polyfill#50] opened 2022-03-03 01:31 UTC
example: https://github.com/JustOff/github-wc-polyfill/network

inside the html is a canvas element which contains the text:

```
Sorry, your browser doesn’t support the <canvas> element.

Please upgrade to the latest Internet Explorer, Chrome or Firefox.
```

**Comment by SeaHOH** [comment] 2022-03-03 03:03
Can't reproduce. Your browser? And maybe it's a network issue.

**Comment by rofl0r** [comment] 2022-03-03 09:08
palemoon 29.4.4

**Comment by SeaHOH** [comment] 2022-03-03 10:39
With 1.2.14b2, still works. You sould try a clean profile.
![nwgraph](https://user-images.githubusercontent.com/8470820/156547868-b20f1186-8dbc-47d7-b5fa-bce28665ecde.png)

**Comment by rofl0r** [comment] 2022-03-03 15:34
thanks for info. do you have a link to 1.2.14b2 comment ? i can't find, still using 1.2.13 as b2 was never officially released.

**Comment by AroKol78** [comment] 2022-03-03 16:13
https://github.com/JustOff/github-wc-polyfill/issues/46#issuecomment-1046181406 or https://github.com/JustOff/github-wc-polyfill/releases/tag/1.2.13 (Assets --> github-wc-polyfill-1.2.14b2.xpi)

**Comment by rofl0r** [comment] 2022-03-03 16:26
thanks. i installed it, restarted palemoon, but it still doesn't work. looks like this:

https://0x0.st/oPm9.png

you're sure you dont use any additional greasemonkey hacks ?

**Comment by AroKol78** [comment] 2022-03-03 16:40
> but it still doesn't work

it doesn't look good for me either (Serpent52)

**Comment by rofl0r** [comment] 2022-03-03 16:46
( just in case someone is asking himself what the purpose of this graph is, it's very handy to find more up-to-date versions of abandoned/unmaintained repos or single bugfix commits )

**Comment by SeaHOH** [comment] 2022-03-03 18:47
> > but it still doesn't work
> 
> it doesn't look good for me either (Serpent52)



> You sould try a clean profile.

**Comment by Vangelis66** [comment] 2022-03-03 22:29
> With **1.2.14b2**, still works. You should try a **clean profile**.

> looks like this: 
>
> ![NG](https://0x0.st/oPm9.png)

> doesn't look good for me either (**Serpent52**)

>> You should try a **clean profile**.

Latest (**UXP**-based) **Serpent** v52.9.0 (2022-02-25) (**32**-bit), clean profile, with **onl**y `1.2.14b2` installed: 

https://github.com/JustOff/github-wc-polyfill/network => 

![NG](https://user-images.githubusercontent.com/9669492/156661337-19692c18-5fa7-4315-93d9-906df3182e88.JPG)

By placing the cursor on the Network Graph "header" and then moving it rightwards, I can reveal previous/past months of the timeline, but not able to display the graph itself... 😞 

In this very machine (besides UXP), I can only test up to a **Chromium 86 fork** (360EEv13), and it, too, exhibits **the same behaviour**; out of curiosity, I borrowed sister's **Win7 SP1 64-bit** laptop and latest stable (97.0.1) **Firefox 32-bit** tells the exact SAME story: 

![Fx97](https://user-images.githubusercontent.com/9669492/156662175-17e64f75-9124-4891-bcbd-ffcda95621f5.jpg)

So, whatever the root cause of this issue is, **doesn't appear related to this extension per se**...
Perhaps it's a GitHub CDN issue, manifested only in certain regions... 
@SeaHOH, are you testing within mainland China? 
Do **Pale Moon 29.4.4 32-bit** and/or official **Basilisk** 52.9.2022.01.27 work as expected at your end?

**Comment by SeaHOH** [comment] 2022-03-04 02:15
His issue is canvas element support.
And yes, the same to your test, the network graph has be overlaid. Most time  the `height` attribute of \<network-graph> (the parent of \<canvas>) has been set to 20+, some time it is a little higher but still incorrect. It's GH own issue.

**Comment by biopsin** [comment] 2022-03-04 07:36
Works for me on PM29.4.4 and 1.2.14b2

![22-03-04--1646379281_scrot](https://user-images.githubusercontent.com/60029989/156719686-4cb20a4d-7f1e-4dd6-a648-50569fa60d47.png)
However it get cut of the rightr end there..

**Comment by AroKol78** [comment] 2022-03-04 16:02
https://github.com/github/feedback/discussions/12061

**Comment by garoto** [comment] 2022-03-04 19:52
Running PM v29.4.4 and seems to be fixed as I write this.

**Comment by AroKol78** [comment] 2022-03-04 20:45
I just checked it out, it's okay now (Serpent52)

**Comment by rofl0r** [comment] 2022-03-04 21:10
great! works now indeed. thanks for all the helpful comments.
let's hope i don't have to reopen this later...

**Comment by garoto** [comment] 2022-03-04 22:52
>  let's hope i don't have to reopen this later...

lol...

Do you even realize where all this garbage website is coded from and by what stereotypical whom.

**Comment by garoto** [comment] 2022-03-04 23:43
Piggybacking this issue to mention that GH is broken again, just like it a couple weeks ago, before all the workarounds and fixes by justoff.

**Comment by rofl0r** [comment] 2022-03-05 01:22
right, it's broken again, together with lots of new issues. should have made a snapshot of all the javascript snippets from 4 hours ago when everything worked.

**Comment by Vangelis66** [comment] 2022-03-05 03:13
> let's hope i don't have to reopen this later...

... but why did you have to jinx it? :smile: 

FWIW, the Network Graph now **renders successfully** in (latest) **Serpent 52**, 

![NG2](https://user-images.githubusercontent.com/9669492/156865421-aee8167a-ade9-4169-bd9e-71b1657fc8c6.JPG)

... so, IMHO, this issue (which, as things turned, was **unrelated to this extension** :wink: ) should be **closed**; in a fashion typical of M$, they did "fix' one thing, but in the process broke so many others... :rage:

**Closed** 2022-03-05 13:37 UTC

**Comment by AroKol78** [comment] 2022-03-06 16:02
1.2.15b6 generally works, only sometimes 
```
Timestamp: 2022-03-06 16:55:26
Error: TypeError: t is undefined
Source File: https://github.githubassets.com/assets/chunk-network-graph-element-cb39f08c.js
Line: 1
``
